const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  ILS: "₪",
  JPY: "¥",
  CAD: "CA$",
  AUD: "A$",
  CHF: "Fr",
  CNY: "¥",
  HKD: "HK$",
  SGD: "S$",
  NZD: "NZ$",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  MXN: "MX$",
  BRL: "R$",
  INR: "₹",
  KRW: "₩",
  ZAR: "R",
  TRY: "₺",
  RUB: "₽",
  PLN: "zł",
  THB: "฿",
  MYR: "RM",
  PHP: "₱",
  SAR: "﷼",
  AED: "د.إ",
  EGP: "E£",
  NGN: "₦",
  CZK: "Kč",
  HUF: "Ft",
  RON: "lei",
  CLP: "CL$",
  COP: "CO$",
  ARS: "AR$",
  IDR: "Rp",
  TWD: "NT$",
  PKR: "₨",
  BDT: "৳",
  VND: "₫",
  UAH: "₴",
  QAR: "﷼",
  KWD: "KD",
  MAD: "MAD",
};

export function getCurrencySymbol(code: string | null | undefined): string {
  if (!code) return "";
  return CURRENCY_SYMBOLS[code] ?? code;
}
